### ISSUE TITLE
teracy-dev roadmap for v0.6.0

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#277]
# v0.6.0
- [ ] project cleanup
- [ ] all Vagrant settings support

**Comment by hoatle** [comment]
let's use https://www.hashicorp.com/blog/hashicorp-vagrant-2-0/ for v0.6.0

**Comment by hoatle** [comment]
this is the proposal for yaml instead of json:

```yaml
# vars must be defined to be used
# format:
# key: ${ENV_VAR}
# key: ${ENV_VAR-:default}
# and "#{key}" can be used for settings values if available
variables:
  node_name_prefix: ${NODE_NAME_PREFIX:-node}
  node_hostname_prefix: ${NODE_HOSTNAME_PREFIX:-teracy-dev}
  some_value: ${MY_VAR:-value}-affix


# vagrant related settings
vagrant:
  require_version: ">= 2.1.0"
  plugins:
    - _id: "0"
      name: vagrant-gatling-rsync
      required: true
      enabled: true
      config_key: gatling
      options:
        latency: 0.5
        time_format: "%H:%M:%S"
        rsync_on_startup: true
    - _id: "1"
      name: vagrant-rsync-back
      required: true
      enabled: true
    - _id: "2"
      name: vagrant-hostmanager
      required: true
      enabled: true
      config_key: hostmanger
      options:
        manage_host: true
        manage_guest: true
  # usually defined from workspace/dev-setup/
  preload_extension_paths:
  postload_extension_paths:
  config_paths:

# teracy-dev related settings
teracy-dev:
  require_version: ">= 0.6.0-a1-SNAPSHOT"
  config_lookup_path: workspace/dev-setup/ # will look for workspace/dev-setup/config_default.yaml

# default settings for all nodes
default:
  vm:
    box: bento/ubuntu-16.04
    box_version:
    box_url:
  providers:
    - _id: "0"
      name: virtualbox
      gui: false
      memory: 1024
      description: "teracy-dev #{Time.now.getutc.to_i}"
  provisioners:
    - _id: "0"
      type: chef_solo
      verion: "13.1.31"
      log_level: info # one of debug, info, warn, error, fatal. Default: info
      cookbooks_path:
        - vendor-cookbooks
        - main-cookbooks
      roles_path: roles
      nodes_path: nodes
      data_bags_path: data_bags
      run_list:
        - vim
        - teracy-dev
      json:
        docker:
          enabled: false
          version: 1.8.0
    - _id: "1"
      type: ansible_local
      # etc


# specific nodes, each node will override the default
nodes:
  - name: "#{node_name_prefix}-1"
    is_primary: true
    vm:
      hostname: "#{NODE_HOSTNAME_PREFIX}-1.local"
  - name: "#{node_name_prefix}-2"
    vm:
      hostname: "#{NODE_HOSTNAME_PREFIX}-2.local"
```
