### ISSUE TITLE
Should support _id update with deprecation

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#501]
we should follow this convention so that when reading the _id, we will know immediately its original config.

Format:
<extension-name\>-<index\>

or:

<extension-name\>-<key-name\>

When the extension-name has `teracy-dev` prefix, remove that prefix.

For example:
- teracy-dev (kernel) => "kernel-0", "kernel-1", etc
- teracy-dev-core => "core-0", "core-1", etc
- teracy-dev-essential => "essential-0", "essential-1", etc.

The _id (by convention) should be unique within an array, so for each array, we should start with the 0 index or use the suitable key name

When updating existing _id, it will create breaking changes because old override config will not work.

Let's see how we can avoid the breaking changes by using deprecation.

**Comment by hoatle** [comment]
we can add `_id_deprecated` field along with the `_id` field. When overriding with the deprecated id, a warning message will be displayed: "The _id: #{old_id} is deprecated, use the _id: #{new_id} instead"

Users can override with the _id's value of _id or _id_deprecated, it should work the same.

After this feature is available, we'll need to update all the existing _id to follow the convention mentioned above.

**Comment by hoatle** [comment]
For example

origin:

```
teracy-dev:
  extensions:
    - _id: "kernel-0"
      _id_deprecated: "0"
      name: hello
```

Override with the deprecated _id will get a warning message:

```
teracy-dev:
  extensions:
    - _id: "0"
      name: hello world
````

Override with the current _id value, it's good.

```
teracy-dev:
  extensions:
    - _id: "kernel-0"
      name: hello world
```
