### ISSUE TITLE
should support "remote" location config from Location::GitSynch

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#502]
This is super convenient for dev mode of extensions so that we don't have to manually configure the remote repos.

format:

```
location:
  git:
    remote:
      origin: <git_repo_origin_url> # must have
      <name>: <git_repo_url>
```

GitSynch must make sure to sync the remotes config here with the actual git remotes of the repo.

Make sure that this is a backward compatible change (deprecating location['git'] origin repo, use location['git']['remote']['origin'] instead).

**Comment by hoatle** [comment]
This is super convenient for working projects within the `workspace` directory.

**Comment by datphan** [comment]
can we have it like this, look simple and git convention like:
```
location:
  git:
    remote:
      origin: <git_repo_origin_url> # must have
      <name>: <git_repo_url>
    main_remote: origin
```

**Comment by hoatle** [comment]
@datphan your proposed change is not backward compatible

**Comment by hoatle** [comment]
@datphan what is the purpose of `main_remote` here? That propose format looks good to me.

**Comment by datphan** [comment]
Something like:
```
git fetch git['remote'][main_remote]
git rebase main_remote/branch
```

If we follow my proposed, in the future we can have more config for diff version control system without conflicts:

```
location:
   git:
      remote: 
      main_remote:
   svn:
     remote: 
     main_remote:
```

**Comment by datphan** [comment]
ofcouse we still have a `deprecated` warning for user

**Comment by hoatle** [comment]
@datphan I'm not sure about the main_remote for now, let's go with your proposed format WITHOUT the main_remote:

```
location:
  git:
    remote:
      origin: <git_repo_origin_url> # must have
      <name>: <git_repo_url>
```

**Comment by hoatle** [comment]
before:

```
location:
  git: <origin_repo_url>
  branch:
  tag: # the same as branch
  ref: # reference hash
  dir: # the check out directory for the 1st time
```

after:

```
location:
  git:
    remote:
      origin: <origin_repo_url>
      <name>: <repo_url>
    branch:
    tag:
    ref:
    dir:
```

**Comment by hoatle** [comment]
when location['git'] is a string of git repo url => use the old deprecated handler and send deprecated message
otherwise, new format is expected.

**Comment by hoatle** [comment]
I guess we could drop "tag" and use "branch" for all, I don't see any reason to keep "tag".

**Comment by hoatle** [comment]
we need to migrate those env vars  (backward compatible required) to match with the new changes https://github.com/teracyhq/dev/blob/develop/lib/teracy-dev/loader.rb#L82

```
      # override/init with env vars if available
      # this is useful to init the teracy-dev-entry or to override existing settings to enable auto sync
      # TERACY_DEV_ENTRY_LOCATION_GIT_REMOTE_ORIGIN, TERACY_DEV_ENTRY_LOCATION_GIT_BRANCH
      # TERACY_DEV_ENTRY_LOCATION_GIT_REF, TERACY_DEV_ENTRY_LOCATION_GIT_SYNC
      location['git']['remote']['origin'] = ENV['TERACY_DEV_ENTRY_LOCATION_GIT_REMOTE_ORIGIN'] if ENV['TERACY_DEV_ENTRY_LOCATION_GIT_REMOTE_ORIGIN']
      location['git']['branch'] = ENV['TERACY_DEV_ENTRY_LOCATION_GIT_BRANCH'] if ENV['TERACY_DEV_ENTRY_LOCATION_GIT_BRANCH']
      location['git']['ref'] = ENV['TERACY_DEV_ENTRY_LOCATION_GIT_REF'] if ENV['TERACY_DEV_ENTRY_LOCATION_GIT_REF']
```

**Comment by hoatle** [comment]
@datphan there is a bug on this.

Create this on the `workspace/teracy-dev-entry/config_default.yaml`

```yaml
teracy-dev:
  extensions:
    - _id: "0"
      location:
        branch: develop
      require_version: ">= 0.4.0-SNAPSHOT"
      enabled: true
```

this works on teracy-dev v0.6.0-a4, but not on v0.6.0-a5-SNAPSHOT

```bash
$ vagrant status
[TeracyDev::Extension::Manager][ERROR]: `>= 0.4.0-SNAPSHOT` is required, but current `0.3.0`: {"_id"=>"0", "path"=>{"lookup"=>"extensions", "extension"=>"teracy-dev-core"}, "location"=>{"git"=>{"remote"=>{"origin"=>"https://github.com/teracyhq-incubator/teracy-dev-core.git"}, "branch"=>"v0.3.0"}, "branch"=>"develop", "lookup_path"=>"/Users/hoatle/teracy-dev/lib/../extensions", "path"=>"/Users/hoatle/teracy-dev/lib/../extensions/teracy-dev-core"}, "require_version"=>">= 0.4.0-SNAPSHOT", "enabled"=>true}
/Users/hoatle/teracy-dev/lib/teracy-dev/extension/manager.rb:54:in `validate'

[TeracyDev::Extension::Manager][ERROR]: The current extension version must be updated to satisfy the requirements above
/Users/hoatle/teracy-dev/lib/teracy-dev/extension/manager.rb:55:in `validate'
```

**Comment by hoatle** [comment]
Expected behavior: there is a use case that update_remote (sync_remote) is always run even sync_existing == true. This will help to update the git remote repos even it's one the extensions or workspace directory.
Actual behavior: no update of remote repos if the extension on at default `extensions` directory.

**Comment by hoatle** [comment]
this line should be remove I guess https://github.com/teracyhq/dev/blob/develop/lib/teracy-dev/location/git_synch.rb#L15

**Comment by datphan** [comment]
I've check and can not reproduce the above when `sync_existing=true`, did you mean `sync_existing=false` instead?

and the setting should be like this:

```
teracy-dev:
  extensions:
    - _id: "0"
      location:
        git:
          branch: develop
      require_version: ">= 0.4.0-SNAPSHOT"
      enabled: true
```

or did you want it to priority location.branch over location.git.branch?
