### ISSUE TITLE
should always use Util.true? for converting boolean values

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#506]
so that we can use string for boolean values instead of just `true` or `false`

Expected:

- `enabled: "true" # or true, "t", "yes", "y", "1"` should be converted as `true`

Actual: only `enabled: true`  is supported.

This is a minor improvement, I thought the following config below would work with the changes from this issue, however, it does not work as the variables processor does not kicks in (hooks) on the teracy-dev-kernel extension config (Maybe we'll think about this later to make this possible).

```
variables:
  my_extension_enabled: ${MY_EXTENSION_ENABLED:-false}

teracy-dev:
    - _id: "entry-my-extension"
      path:
        extension: project/teracy-dev-my-extension
      location:
        git: git@github.com:org/project.git
        branch: develop
      require_version: ">= 0.1.0-SNAPSHOT"
      enabled: "%{my_extension_enabled}"
```
