### ISSUE TITLE
should handle the extension sync properly when it is within a repo

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#527]
for example with this config:

```
 - _id: "entry-iorad-app"
      path:
        lookup: workspace
        extension: iorad/teracy-dev-iorad-app # convert from https://github.com/iorad/iorad/tree/develop/dev-setup
      location:
        git:
          remote:
            origin: git@github.com:iorad/iorad.git
            branch: develop
      require_version: ">= 0.1.0-SNAPSHOT"
      enabled: true
```

- expected:

```
[TeracyDev::Location::GitSynch][INFO]: cd /Users/hoatle/iorad-dev-2/lib/../workspace/iorad && git checkout develop
```

```
iorad$ git remote -v
origin    git@github.com:iorad/iorad.git (fetch)
origin    git@github.com:iorad/iorad.git (push)
```

- actual:

```
[TeracyDev::Location::GitSynch][INFO]: cd /Users/hoatle/iorad-dev-2/lib/../workspace/iorad/teracy-dev-iorad-app && git checkout master
/Users/hoatle/iorad-dev-2/lib/teracy-dev/location/git_synch.rb:98:in `block in sync'

Branch 'master' set up to track remote branch 'master' from 'origin'.
Switched to a new branch 'master'
fatal: No such remote: branch
```

```
iorad$ git remote -v
branch    develop (fetch)
branch    develop (push)
origin    git@github.com:iorad/iorad.git (fetch)
origin    git@github.com:iorad/iorad.git (push)
```

**Comment by hoatle** [comment]
note: due to the wrong config, the `$ git remote -v` error is expected, we'll handle this case (validate later by #495)

```
       git:
          remote:
            origin: git@github.com:iorad/iorad.git
            branch: develop
```

should be:

```
       git:
          remote:
            origin: git@github.com:iorad/iorad.git
          branch: develop
```
