### ISSUE TITLE
"fatal: No such remote:" should not be displayed when a new git remote repo config is added

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#534]
steps to reproduce:

- initial config:

```
teracy-dev:
  extensions:

    - _id: "entry-certs"
      path:
        extension: teracy-dev-certs
      location:
        git:
          remote:
            origin: git@github.com:teracyhq-incubator/teracy-dev-certs.git
            upstream: git@github.com:teracyhq-incubator/teracy-dev-certs.git
          branch: develop
      require_version: ">= 0.1.0-SNAPSHOT"
      enabled: true
```
then `$ vagrant status` to see that it works as expected

- now add more git remote repo:

```
teracy-dev:
  extensions:

    - _id: "entry-certs"
      path:
        extension: teracy-dev-certs
      location:
        git:
          remote:
            origin: git@github.com:teracyhq-incubator/teracy-dev-certs.git
            upstream: git@github.com:teracyhq-incubator/teracy-dev-certs.git
          branch: develop
      require_version: ">= 0.1.0-SNAPSHOT"
      enabled: true
```

then `$ vagrant status` again

- Expected: upstream remote repo is added without any problem

- Actual: the console output "fatal", this is not expected console output.

```
macbook-pro:teracy-dev hoatle$ vagrant status
fatal: No such remote: upstream
Current machine states:

node-01                   poweroff (virtualbox)

The VM is powered off. To restart the VM, simply run `vagrant up`
```
