### ISSUE TITLE
teracy-dev-entry should update its git remote repos even if sync is false

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#535]
steps:

- Clone https://github.com/teracyhq-incubator/teracy-dev-entry-k8s.git into the workspace directory with `teracy-dev-entry` name:

```
$ cd workspace
$ git clone https://github.com/teracyhq-incubator/teracy-dev-entry-k8s.git teracy-dev-entry
```

- Update the config of `workspace/teracy-dev-entry/config_default.yaml`:

```
teracy-dev:
  entry_location:
    git:
      remote:
        origin: https://github.com/teracyhq-incubator/teracy-dev-entry-k8s.git
        upstream: https://github.com/teracyhq-incubator/teracy-dev-entry-k8s.git
      branch: develop
    sync: false
```
and `$ vagrant status` to make sure everything is updated

- Expected:

```
$ cd workspace/teracy-dev-entry
$ git remote -v
```
should display the origin and upstream repos

- Actual:

upstream remote repo was not added
