### ISSUE TITLE
Util.override with nil source should return the origin object

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#574]
expected:
Util.override(obj, nil) => return obj

actual: return nil

This use case happens with my empty yaml key sometimes (when commenting):

```yaml
teracy-dev-certs:
  ansible: 
    mode: host
```

and this did not work as expected

```yaml
teracy-dev-certs:
  ansible: 
    # mode: host
```
